### ISSUE TITLE
GitHub Releases

### ISSUE THREAD

**Issue by xilopaint** [Acidham/search-alfred-workflows#10]
Do you consider to make releases? The releases page is the best place to keep track of workflow updates and its new features.

Also, you can setup OneUpdater to work with GitHub releases.

**Comment by Acidham** [comment]
@xilopaint Yes you are right. I never expected contributors or interest to that workflow ;)
I will take a look at it next ween when I am back from vacation!

**Comment by Acidham** [comment]
> Also, you can setup OneUpdater to work with GitHub releases.

I tried this in the past but did never work for me. Any idea what is required when I create a release in OneUpdater:

> workflow_url must be of the form username/repo.

Would it be `acidham/search-alfred-workflow` or something different?

**Comment by xilopaint** [comment]
> Would it be `acidham/search-alfred-workflow` or something different?

`acidham/search-alfred-workflow`

**Comment by Acidham** [comment]
Done with  v0.7.7
