### ISSUE TITLE
What to change so I can instantly open workflow in Alfred Preferences on return key

### ISSUE THREAD

**Issue by nikitavoloboev** [Acidham/search-alfred-workflows#7]
I want to only search the list of workflows and on return open the workflow in Alfred Preferences as that's all I care about.

Can I just move this block and connect?

![2019-06-07 at 23 09](https://user-images.githubusercontent.com/6391776/59136046-4436c900-8979-11e9-80a8-a4974fc6f389.png)

Or I have to do something else?

**Comment by Acidham** [comment]
you said "only care about" open in Alfred. To do this try the blue line but remove the CMD connection and the other connections.
![Screen Shot 2019-06-08 at 00 17 41](https://user-images.githubusercontent.com/17712121/59136436-71887480-8983-11e9-8648-be034a8f7409.png)

**Comment by nikitavoloboev** [comment]
Thanks
